# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_cityEX_16_02.ui'
#
# Created: Mon Feb 16 18:50:19 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CityEX(object):
    def setupUi(self, CityEX):
        CityEX.setObjectName(_fromUtf8("CityEX"))
        CityEX.resize(390, 666)
        CityEX.setMinimumSize(QtCore.QSize(0, 666))
        CityEX.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        CityEX.setFont(font)
        self.tabWidget_main = QtGui.QTabWidget(CityEX)
        self.tabWidget_main.setGeometry(QtCore.QRect(0, 0, 390, 630))
        self.tabWidget_main.setMinimumSize(QtCore.QSize(350, 630))
        self.tabWidget_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_main.setObjectName(_fromUtf8("tabWidget_main"))
        self.Mainwindow = QtGui.QWidget()
        self.Mainwindow.setObjectName(_fromUtf8("Mainwindow"))
        self.lineEdit_tab1_input_dem = QtGui.QLineEdit(self.Mainwindow)
        self.lineEdit_tab1_input_dem.setGeometry(QtCore.QRect(35, 80, 250, 20))
        self.lineEdit_tab1_input_dem.setObjectName(_fromUtf8("lineEdit_tab1_input_dem"))
        self.lineEdit_tab1_input_dom = QtGui.QLineEdit(self.Mainwindow)
        self.lineEdit_tab1_input_dom.setGeometry(QtCore.QRect(35, 120, 250, 20))
        self.lineEdit_tab1_input_dom.setObjectName(_fromUtf8("lineEdit_tab1_input_dom"))
        self.lineEdit_tab1_support = QtGui.QLineEdit(self.Mainwindow)
        self.lineEdit_tab1_support.setGeometry(QtCore.QRect(35, 340, 250, 20))
        self.lineEdit_tab1_support.setObjectName(_fromUtf8("lineEdit_tab1_support"))
        self.lineEdit_tab1_output = QtGui.QLineEdit(self.Mainwindow)
        self.lineEdit_tab1_output.setGeometry(QtCore.QRect(35, 560, 250, 20))
        self.lineEdit_tab1_output.setObjectName(_fromUtf8("lineEdit_tab1_output"))
        self.comboBox_tab1_input = QtGui.QComboBox(self.Mainwindow)
        self.comboBox_tab1_input.setGeometry(QtCore.QRect(35, 40, 170, 20))
        self.comboBox_tab1_input.setObjectName(_fromUtf8("comboBox_tab1_input"))
        self.comboBox_tab1_input.addItem(_fromUtf8(""))
        self.comboBox_tab1_input.addItem(_fromUtf8(""))
        self.comboBox_tab1_input.addItem(_fromUtf8(""))
        self.pushButton_tab1_input_dom = QtGui.QPushButton(self.Mainwindow)
        self.pushButton_tab1_input_dom.setGeometry(QtCore.QRect(295, 120, 69, 20))
        self.pushButton_tab1_input_dom.setObjectName(_fromUtf8("pushButton_tab1_input_dom"))
        self.pushButton_tab1_input_dem = QtGui.QPushButton(self.Mainwindow)
        self.pushButton_tab1_input_dem.setGeometry(QtCore.QRect(295, 80, 69, 20))
        self.pushButton_tab1_input_dem.setObjectName(_fromUtf8("pushButton_tab1_input_dem"))
        self.pushButton_tab1_input_support = QtGui.QPushButton(self.Mainwindow)
        self.pushButton_tab1_input_support.setGeometry(QtCore.QRect(295, 340, 69, 20))
        self.pushButton_tab1_input_support.setObjectName(_fromUtf8("pushButton_tab1_input_support"))
        self.pushButton_tab1_output = QtGui.QPushButton(self.Mainwindow)
        self.pushButton_tab1_output.setGeometry(QtCore.QRect(295, 560, 69, 20))
        self.pushButton_tab1_output.setObjectName(_fromUtf8("pushButton_tab1_output"))
        self.label_input = QtGui.QLabel(self.Mainwindow)
        self.label_input.setGeometry(QtCore.QRect(90, 10, 210, 20))
        self.label_input.setObjectName(_fromUtf8("label_input"))
        self.label_support = QtGui.QLabel(self.Mainwindow)
        self.label_support.setGeometry(QtCore.QRect(95, 270, 200, 20))
        self.label_support.setObjectName(_fromUtf8("label_support"))
        self.comboBox_tab1_support = QtGui.QComboBox(self.Mainwindow)
        self.comboBox_tab1_support.setGeometry(QtCore.QRect(35, 300, 170, 20))
        self.comboBox_tab1_support.setObjectName(_fromUtf8("comboBox_tab1_support"))
        self.comboBox_tab1_support.addItem(_fromUtf8(""))
        self.comboBox_tab1_support.addItem(_fromUtf8(""))
        self.comboBox_tab1_support.addItem(_fromUtf8(""))
        self.comboBox_tab1_support.addItem(_fromUtf8(""))
        self.comboBox_tab1_red = QtGui.QComboBox(self.Mainwindow)
        self.comboBox_tab1_red.setGeometry(QtCore.QRect(115, 380, 69, 20))
        self.comboBox_tab1_red.setObjectName(_fromUtf8("comboBox_tab1_red"))
        self.comboBox_tab1_ir = QtGui.QComboBox(self.Mainwindow)
        self.comboBox_tab1_ir.setGeometry(QtCore.QRect(295, 380, 69, 20))
        self.comboBox_tab1_ir.setObjectName(_fromUtf8("comboBox_tab1_ir"))
        self.doubleSpinBox_tab1_cellsize = QtGui.QDoubleSpinBox(self.Mainwindow)
        self.doubleSpinBox_tab1_cellsize.setGeometry(QtCore.QRect(105, 160, 69, 20))
        self.doubleSpinBox_tab1_cellsize.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tab1_cellsize.setMaximum(200.0)
        self.doubleSpinBox_tab1_cellsize.setSingleStep(0.5)
        self.doubleSpinBox_tab1_cellsize.setObjectName(_fromUtf8("doubleSpinBox_tab1_cellsize"))
        self.label_cell = QtGui.QLabel(self.Mainwindow)
        self.label_cell.setGeometry(QtCore.QRect(35, 160, 61, 20))
        self.label_cell.setObjectName(_fromUtf8("label_cell"))
        self.label_epsg = QtGui.QLabel(self.Mainwindow)
        self.label_epsg.setGeometry(QtCore.QRect(195, 160, 101, 20))
        self.label_epsg.setObjectName(_fromUtf8("label_epsg"))
        self.spinBox_tab1_EPSG = QtGui.QSpinBox(self.Mainwindow)
        self.spinBox_tab1_EPSG.setGeometry(QtCore.QRect(295, 160, 69, 20))
        self.spinBox_tab1_EPSG.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_tab1_EPSG.setMaximum(100000)
        self.spinBox_tab1_EPSG.setObjectName(_fromUtf8("spinBox_tab1_EPSG"))
        self.line = QtGui.QFrame(self.Mainwindow)
        self.line.setGeometry(QtCore.QRect(20, 250, 350, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_band_red = QtGui.QLabel(self.Mainwindow)
        self.label_band_red.setGeometry(QtCore.QRect(35, 380, 71, 20))
        self.label_band_red.setObjectName(_fromUtf8("label_band_red"))
        self.label_band_ifrared = QtGui.QLabel(self.Mainwindow)
        self.label_band_ifrared.setGeometry(QtCore.QRect(195, 380, 101, 20))
        self.label_band_ifrared.setObjectName(_fromUtf8("label_band_ifrared"))
        self.line_3 = QtGui.QFrame(self.Mainwindow)
        self.line_3.setGeometry(QtCore.QRect(20, 420, 350, 3))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_output = QtGui.QLabel(self.Mainwindow)
        self.label_output.setGeometry(QtCore.QRect(115, 430, 160, 20))
        self.label_output.setObjectName(_fromUtf8("label_output"))
        self.checkBox_tab1_buildings = QtGui.QCheckBox(self.Mainwindow)
        self.checkBox_tab1_buildings.setGeometry(QtCore.QRect(35, 460, 91, 20))
        self.checkBox_tab1_buildings.setObjectName(_fromUtf8("checkBox_tab1_buildings"))
        self.checkBox_tab1_trees = QtGui.QCheckBox(self.Mainwindow)
        self.checkBox_tab1_trees.setGeometry(QtCore.QRect(185, 460, 61, 20))
        self.checkBox_tab1_trees.setObjectName(_fromUtf8("checkBox_tab1_trees"))
        self.checkBox_tab1_ndem = QtGui.QCheckBox(self.Mainwindow)
        self.checkBox_tab1_ndem.setGeometry(QtCore.QRect(300, 460, 71, 20))
        self.checkBox_tab1_ndem.setObjectName(_fromUtf8("checkBox_tab1_ndem"))
        self.label_nodata = QtGui.QLabel(self.Mainwindow)
        self.label_nodata.setGeometry(QtCore.QRect(110, 210, 100, 20))
        self.label_nodata.setObjectName(_fromUtf8("label_nodata"))
        self.spinBox_tab1_nodata = QtGui.QSpinBox(self.Mainwindow)
        self.spinBox_tab1_nodata.setGeometry(QtCore.QRect(220, 210, 69, 20))
        self.spinBox_tab1_nodata.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_tab1_nodata.setMinimum(-100000)
        self.spinBox_tab1_nodata.setMaximum(100000)
        self.spinBox_tab1_nodata.setObjectName(_fromUtf8("spinBox_tab1_nodata"))
        self.tabWidget_main.addTab(self.Mainwindow, _fromUtf8(""))
        self.building_filter = QtGui.QWidget()
        self.building_filter.setObjectName(_fromUtf8("building_filter"))
        self.tableWidget_tab2_knowlegde = QtGui.QTableWidget(self.building_filter)
        self.tableWidget_tab2_knowlegde.setGeometry(QtCore.QRect(20, 50, 350, 200))
        self.tableWidget_tab2_knowlegde.setObjectName(_fromUtf8("tableWidget_tab2_knowlegde"))
        self.tableWidget_tab2_knowlegde.setColumnCount(3)
        self.tableWidget_tab2_knowlegde.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tab2_knowlegde.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tab2_knowlegde.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tab2_knowlegde.setHorizontalHeaderItem(2, item)
        self.label_knowlegde = QtGui.QLabel(self.building_filter)
        self.label_knowlegde.setGeometry(QtCore.QRect(90, 20, 210, 20))
        self.label_knowlegde.setObjectName(_fromUtf8("label_knowlegde"))
        self.label_filter = QtGui.QLabel(self.building_filter)
        self.label_filter.setGeometry(QtCore.QRect(145, 320, 100, 20))
        self.label_filter.setObjectName(_fromUtf8("label_filter"))
        self.spinBox_tab2_x_erosion = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_x_erosion.setGeometry(QtCore.QRect(170, 450, 60, 20))
        self.spinBox_tab2_x_erosion.setMinimum(1)
        self.spinBox_tab2_x_erosion.setMaximum(999)
        self.spinBox_tab2_x_erosion.setObjectName(_fromUtf8("spinBox_tab2_x_erosion"))
        self.spinBox_tab2_y_erosion = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_y_erosion.setGeometry(QtCore.QRect(310, 450, 60, 20))
        self.spinBox_tab2_y_erosion.setMinimum(1)
        self.spinBox_tab2_y_erosion.setMaximum(999)
        self.spinBox_tab2_y_erosion.setObjectName(_fromUtf8("spinBox_tab2_y_erosion"))
        self.spinBox_tab2_x_opening = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_x_opening.setGeometry(QtCore.QRect(170, 410, 60, 20))
        self.spinBox_tab2_x_opening.setMinimum(1)
        self.spinBox_tab2_x_opening.setMaximum(999)
        self.spinBox_tab2_x_opening.setObjectName(_fromUtf8("spinBox_tab2_x_opening"))
        self.spinBox_tab2_y_opening = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_y_opening.setGeometry(QtCore.QRect(310, 410, 60, 20))
        self.spinBox_tab2_y_opening.setMinimum(1)
        self.spinBox_tab2_y_opening.setMaximum(999)
        self.spinBox_tab2_y_opening.setObjectName(_fromUtf8("spinBox_tab2_y_opening"))
        self.spinBox_tab2_x_closing = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_x_closing.setGeometry(QtCore.QRect(170, 370, 60, 20))
        self.spinBox_tab2_x_closing.setMinimum(1)
        self.spinBox_tab2_x_closing.setMaximum(999)
        self.spinBox_tab2_x_closing.setObjectName(_fromUtf8("spinBox_tab2_x_closing"))
        self.spinBox_tab2_y_closing = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_y_closing.setGeometry(QtCore.QRect(310, 370, 60, 20))
        self.spinBox_tab2_y_closing.setMinimum(1)
        self.spinBox_tab2_y_closing.setMaximum(999)
        self.spinBox_tab2_y_closing.setObjectName(_fromUtf8("spinBox_tab2_y_closing"))
        self.checkBox_tab2_erosion = QtGui.QCheckBox(self.building_filter)
        self.checkBox_tab2_erosion.setGeometry(QtCore.QRect(20, 450, 81, 20))
        self.checkBox_tab2_erosion.setObjectName(_fromUtf8("checkBox_tab2_erosion"))
        self.checkBox_tab2_opening = QtGui.QCheckBox(self.building_filter)
        self.checkBox_tab2_opening.setGeometry(QtCore.QRect(20, 410, 81, 20))
        self.checkBox_tab2_opening.setObjectName(_fromUtf8("checkBox_tab2_opening"))
        self.checkBox_tab2_closing = QtGui.QCheckBox(self.building_filter)
        self.checkBox_tab2_closing.setGeometry(QtCore.QRect(20, 370, 81, 20))
        self.checkBox_tab2_closing.setObjectName(_fromUtf8("checkBox_tab2_closing"))
        self.checkBox_tab2_fillhole = QtGui.QCheckBox(self.building_filter)
        self.checkBox_tab2_fillhole.setGeometry(QtCore.QRect(20, 490, 91, 20))
        self.checkBox_tab2_fillhole.setObjectName(_fromUtf8("checkBox_tab2_fillhole"))
        self.pushButton_tab2_add = QtGui.QPushButton(self.building_filter)
        self.pushButton_tab2_add.setGeometry(QtCore.QRect(20, 270, 90, 20))
        self.pushButton_tab2_add.setObjectName(_fromUtf8("pushButton_tab2_add"))
        self.pushButton_tab2_delete = QtGui.QPushButton(self.building_filter)
        self.pushButton_tab2_delete.setGeometry(QtCore.QRect(280, 270, 90, 20))
        self.pushButton_tab2_delete.setObjectName(_fromUtf8("pushButton_tab2_delete"))
        self.line_2 = QtGui.QFrame(self.building_filter)
        self.line_2.setGeometry(QtCore.QRect(20, 310, 350, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.spinBox_tab2_y_filling = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_y_filling.setGeometry(QtCore.QRect(310, 490, 60, 20))
        self.spinBox_tab2_y_filling.setMinimum(1)
        self.spinBox_tab2_y_filling.setMaximum(999)
        self.spinBox_tab2_y_filling.setObjectName(_fromUtf8("spinBox_tab2_y_filling"))
        self.spinBox_tab2_x_filling = QtGui.QSpinBox(self.building_filter)
        self.spinBox_tab2_x_filling.setGeometry(QtCore.QRect(170, 490, 60, 20))
        self.spinBox_tab2_x_filling.setMinimum(1)
        self.spinBox_tab2_x_filling.setMaximum(999)
        self.spinBox_tab2_x_filling.setObjectName(_fromUtf8("spinBox_tab2_x_filling"))
        self.label_19 = QtGui.QLabel(self.building_filter)
        self.label_19.setGeometry(QtCore.QRect(310, 340, 60, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.building_filter)
        self.label_20.setGeometry(QtCore.QRect(170, 340, 60, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_object_3 = QtGui.QLabel(self.building_filter)
        self.label_object_3.setGeometry(QtCore.QRect(20, 560, 231, 20))
        self.label_object_3.setObjectName(_fromUtf8("label_object_3"))
        self.doubleSpinBox_tab2_area = QtGui.QDoubleSpinBox(self.building_filter)
        self.doubleSpinBox_tab2_area.setGeometry(QtCore.QRect(310, 560, 60, 20))
        self.doubleSpinBox_tab2_area.setMaximum(10000.0)
        self.doubleSpinBox_tab2_area.setSingleStep(0.5)
        self.doubleSpinBox_tab2_area.setObjectName(_fromUtf8("doubleSpinBox_tab2_area"))
        self.line_5 = QtGui.QFrame(self.building_filter)
        self.line_5.setGeometry(QtCore.QRect(20, 540, 350, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.tabWidget_main.addTab(self.building_filter, _fromUtf8(""))
        self.TreeFilter = QtGui.QWidget()
        self.TreeFilter.setObjectName(_fromUtf8("TreeFilter"))
        self.label_knowlegde_2 = QtGui.QLabel(self.TreeFilter)
        self.label_knowlegde_2.setGeometry(QtCore.QRect(90, 20, 210, 20))
        self.label_knowlegde_2.setObjectName(_fromUtf8("label_knowlegde_2"))
        self.tableWidget_tab3_knowlegde = QtGui.QTableWidget(self.TreeFilter)
        self.tableWidget_tab3_knowlegde.setGeometry(QtCore.QRect(20, 50, 350, 200))
        self.tableWidget_tab3_knowlegde.setObjectName(_fromUtf8("tableWidget_tab3_knowlegde"))
        self.tableWidget_tab3_knowlegde.setColumnCount(3)
        self.tableWidget_tab3_knowlegde.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tab3_knowlegde.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tab3_knowlegde.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_tab3_knowlegde.setHorizontalHeaderItem(2, item)
        self.spinBox_tab3_iter = QtGui.QSpinBox(self.TreeFilter)
        self.spinBox_tab3_iter.setGeometry(QtCore.QRect(310, 500, 60, 20))
        self.spinBox_tab3_iter.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_tab3_iter.setMinimum(1)
        self.spinBox_tab3_iter.setMaximum(999)
        self.spinBox_tab3_iter.setObjectName(_fromUtf8("spinBox_tab3_iter"))
        self.label_tab3_iter = QtGui.QLabel(self.TreeFilter)
        self.label_tab3_iter.setGeometry(QtCore.QRect(20, 500, 151, 20))
        self.label_tab3_iter.setObjectName(_fromUtf8("label_tab3_iter"))
        self.label_tab3_iter_2 = QtGui.QLabel(self.TreeFilter)
        self.label_tab3_iter_2.setGeometry(QtCore.QRect(20, 540, 91, 20))
        self.label_tab3_iter_2.setObjectName(_fromUtf8("label_tab3_iter_2"))
        self.spinBox_tab3_windowsize = QtGui.QSpinBox(self.TreeFilter)
        self.spinBox_tab3_windowsize.setGeometry(QtCore.QRect(310, 540, 60, 20))
        self.spinBox_tab3_windowsize.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_tab3_windowsize.setMinimum(1)
        self.spinBox_tab3_windowsize.setMaximum(999)
        self.spinBox_tab3_windowsize.setObjectName(_fromUtf8("spinBox_tab3_windowsize"))
        self.line_4 = QtGui.QFrame(self.TreeFilter)
        self.line_4.setGeometry(QtCore.QRect(20, 310, 350, 3))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_17 = QtGui.QLabel(self.TreeFilter)
        self.label_17.setGeometry(QtCore.QRect(170, 350, 60, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.TreeFilter)
        self.label_18.setGeometry(QtCore.QRect(310, 350, 60, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.spinBox_tab3_y_closing = QtGui.QSpinBox(self.TreeFilter)
        self.spinBox_tab3_y_closing.setGeometry(QtCore.QRect(310, 380, 60, 20))
        self.spinBox_tab3_y_closing.setMinimum(1)
        self.spinBox_tab3_y_closing.setMaximum(999)
        self.spinBox_tab3_y_closing.setObjectName(_fromUtf8("spinBox_tab3_y_closing"))
        self.checkBox_tab3_closing = QtGui.QCheckBox(self.TreeFilter)
        self.checkBox_tab3_closing.setGeometry(QtCore.QRect(20, 380, 75, 21))
        self.checkBox_tab3_closing.setObjectName(_fromUtf8("checkBox_tab3_closing"))
        self.spinBox_tab3_x_closing = QtGui.QSpinBox(self.TreeFilter)
        self.spinBox_tab3_x_closing.setGeometry(QtCore.QRect(170, 380, 60, 20))
        self.spinBox_tab3_x_closing.setMinimum(1)
        self.spinBox_tab3_x_closing.setMaximum(999)
        self.spinBox_tab3_x_closing.setObjectName(_fromUtf8("spinBox_tab3_x_closing"))
        self.label_filter_2 = QtGui.QLabel(self.TreeFilter)
        self.label_filter_2.setGeometry(QtCore.QRect(160, 320, 100, 20))
        self.label_filter_2.setObjectName(_fromUtf8("label_filter_2"))
        self.label_tab3_allowed = QtGui.QLabel(self.TreeFilter)
        self.label_tab3_allowed.setGeometry(QtCore.QRect(20, 420, 191, 20))
        self.label_tab3_allowed.setObjectName(_fromUtf8("label_tab3_allowed"))
        self.spinBox_tab3_nodata_allowed = QtGui.QSpinBox(self.TreeFilter)
        self.spinBox_tab3_nodata_allowed.setGeometry(QtCore.QRect(310, 420, 60, 20))
        self.spinBox_tab3_nodata_allowed.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_tab3_nodata_allowed.setMinimum(0)
        self.spinBox_tab3_nodata_allowed.setMaximum(100)
        self.spinBox_tab3_nodata_allowed.setProperty(_fromUtf8("value"), 0)
        self.spinBox_tab3_nodata_allowed.setObjectName(_fromUtf8("spinBox_tab3_nodata_allowed"))
        self.doubleSpinBox_tab3_cri_value = QtGui.QDoubleSpinBox(self.TreeFilter)
        self.doubleSpinBox_tab3_cri_value.setGeometry(QtCore.QRect(310, 460, 60, 20))
        self.doubleSpinBox_tab3_cri_value.setAutoFillBackground(False)
        self.doubleSpinBox_tab3_cri_value.setWrapping(False)
        self.doubleSpinBox_tab3_cri_value.setFrame(True)
        self.doubleSpinBox_tab3_cri_value.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tab3_cri_value.setMaximum(100.0)
        self.doubleSpinBox_tab3_cri_value.setSingleStep(0.5)
        self.doubleSpinBox_tab3_cri_value.setObjectName(_fromUtf8("doubleSpinBox_tab3_cri_value"))
        self.label_tab3_crit_height = QtGui.QLabel(self.TreeFilter)
        self.label_tab3_crit_height.setGeometry(QtCore.QRect(20, 460, 191, 20))
        self.label_tab3_crit_height.setObjectName(_fromUtf8("label_tab3_crit_height"))
        self.pushButton_tab3_delete = QtGui.QPushButton(self.TreeFilter)
        self.pushButton_tab3_delete.setGeometry(QtCore.QRect(280, 270, 90, 20))
        self.pushButton_tab3_delete.setObjectName(_fromUtf8("pushButton_tab3_delete"))
        self.pushButton_tab3_add = QtGui.QPushButton(self.TreeFilter)
        self.pushButton_tab3_add.setGeometry(QtCore.QRect(20, 270, 90, 20))
        self.pushButton_tab3_add.setObjectName(_fromUtf8("pushButton_tab3_add"))
        self.tabWidget_main.addTab(self.TreeFilter, _fromUtf8(""))
        self.Help = QtGui.QWidget()
        self.Help.setObjectName(_fromUtf8("Help"))
        self.treeWidget_tab4_help = QtGui.QTreeWidget(self.Help)
        self.treeWidget_tab4_help.setGeometry(QtCore.QRect(20, 10, 350, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_tab4_help.setFont(font)
        self.treeWidget_tab4_help.setObjectName(_fromUtf8("treeWidget_tab4_help"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_tab4_help)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_tab4_help)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_tab4_help)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_tab4_help)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.textEdit_tab4_help = QtGui.QTextEdit(self.Help)
        self.textEdit_tab4_help.setGeometry(QtCore.QRect(20, 240, 350, 340))
        self.textEdit_tab4_help.setObjectName(_fromUtf8("textEdit_tab4_help"))
        self.tabWidget_main.addTab(self.Help, _fromUtf8(""))
        self.pushButton_global_cancel = QtGui.QPushButton(CityEX)
        self.pushButton_global_cancel.setGeometry(QtCore.QRect(300, 638, 69, 20))
        self.pushButton_global_cancel.setObjectName(_fromUtf8("pushButton_global_cancel"))
        self.pushButton_global_ok = QtGui.QPushButton(CityEX)
        self.pushButton_global_ok.setGeometry(QtCore.QRect(210, 638, 69, 20))
        self.pushButton_global_ok.setObjectName(_fromUtf8("pushButton_global_ok"))
        self.lineEdit_global_error = QtGui.QLineEdit(CityEX)
        self.lineEdit_global_error.setGeometry(QtCore.QRect(10, 638, 180, 20))
        self.lineEdit_global_error.setAcceptDrops(False)
        self.lineEdit_global_error.setReadOnly(True)
        self.lineEdit_global_error.setObjectName(_fromUtf8("lineEdit_global_error"))

        self.retranslateUi(CityEX)
        self.tabWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CityEX)

    def retranslateUi(self, CityEX):
        CityEX.setWindowTitle(QtGui.QApplication.translate("CityEX", "CityEX", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tab1_input.setItemText(0, QtGui.QApplication.translate("CityEX", "Choose input", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tab1_input.setItemText(1, QtGui.QApplication.translate("CityEX", "Normalized DEM", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tab1_input.setItemText(2, QtGui.QApplication.translate("CityEX", "DEM & DOM", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab1_input_dom.setText(QtGui.QApplication.translate("CityEX", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab1_input_dem.setText(QtGui.QApplication.translate("CityEX", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab1_input_support.setText(QtGui.QApplication.translate("CityEX", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab1_output.setText(QtGui.QApplication.translate("CityEX", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_input.setText(QtGui.QApplication.translate("CityEX", "Choose your input data type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_support.setText(QtGui.QApplication.translate("CityEX", "Choose your support data:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tab1_support.setItemText(0, QtGui.QApplication.translate("CityEX", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tab1_support.setItemText(1, QtGui.QApplication.translate("CityEX", "RGB + IR - Image", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tab1_support.setItemText(2, QtGui.QApplication.translate("CityEX", "NDVI", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tab1_support.setItemText(3, QtGui.QApplication.translate("CityEX", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cell.setText(QtGui.QApplication.translate("CityEX", "Cell size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_epsg.setText(QtGui.QApplication.translate("CityEX", "EPSG - Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_band_red.setText(QtGui.QApplication.translate("CityEX", "Red Band:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_band_ifrared.setText(QtGui.QApplication.translate("CityEX", "Infrared Band:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_output.setText(QtGui.QApplication.translate("CityEX", "Choose your outputs: ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab1_buildings.setText(QtGui.QApplication.translate("CityEX", "Buildings", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab1_trees.setText(QtGui.QApplication.translate("CityEX", "Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab1_ndem.setText(QtGui.QApplication.translate("CityEX", "nDEM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nodata.setText(QtGui.QApplication.translate("CityEX", "No data value:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.Mainwindow), QtGui.QApplication.translate("CityEX", "Mainwindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tab2_knowlegde.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("CityEX", "On which data?", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tab2_knowlegde.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("CityEX", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tab2_knowlegde.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("CityEX", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_knowlegde.setText(QtGui.QApplication.translate("CityEX", "Knowlegde based assuptions:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_filter.setText(QtGui.QApplication.translate("CityEX", "Filter options:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab2_erosion.setText(QtGui.QApplication.translate("CityEX", "Erosion", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab2_opening.setText(QtGui.QApplication.translate("CityEX", "Opening", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab2_closing.setText(QtGui.QApplication.translate("CityEX", "Closing", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab2_fillhole.setText(QtGui.QApplication.translate("CityEX", "Fill Holes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab2_add.setText(QtGui.QApplication.translate("CityEX", "Add Row", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab2_delete.setText(QtGui.QApplication.translate("CityEX", "Delete Row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("CityEX", "Y - Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("CityEX", "X- Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_object_3.setText(QtGui.QApplication.translate("CityEX", "Remove structures smaller than:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.building_filter), QtGui.QApplication.translate("CityEX", "Building Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_knowlegde_2.setText(QtGui.QApplication.translate("CityEX", "Knowlegde based assuptions:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tab3_knowlegde.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("CityEX", "On which data?", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tab3_knowlegde.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("CityEX", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_tab3_knowlegde.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("CityEX", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab3_iter.setText(QtGui.QApplication.translate("CityEX", "Number of iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab3_iter_2.setText(QtGui.QApplication.translate("CityEX", "Windowsize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("CityEX", "X- Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("CityEX", "Y - Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_tab3_closing.setText(QtGui.QApplication.translate("CityEX", "Closing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_filter_2.setText(QtGui.QApplication.translate("CityEX", "Filter rules:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab3_allowed.setText(QtGui.QApplication.translate("CityEX", "Allowd no data percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab3_crit_height.setText(QtGui.QApplication.translate("CityEX", "Critical tree top height", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab3_delete.setText(QtGui.QApplication.translate("CityEX", "Delete Row", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tab3_add.setText(QtGui.QApplication.translate("CityEX", "Add Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.TreeFilter), QtGui.QApplication.translate("CityEX", "Tree Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.headerItem().setText(0, QtGui.QApplication.translate("CityEX", "Information about the program", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_tab4_help.isSortingEnabled()
        self.treeWidget_tab4_help.setSortingEnabled(False)
        self.treeWidget_tab4_help.topLevelItem(0).setText(0, QtGui.QApplication.translate("CityEX", "Mainwindow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("CityEX", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("CityEX", "Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(1).setText(0, QtGui.QApplication.translate("CityEX", "Building Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("CityEX", "Close Holes", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(2).setText(0, QtGui.QApplication.translate("CityEX", "Tree Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(2).child(0).setText(0, QtGui.QApplication.translate("CityEX", "Creating rules", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(2).child(1).setText(0, QtGui.QApplication.translate("CityEX", "Closing filter", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(2).child(2).setText(0, QtGui.QApplication.translate("CityEX", "Critical tree top height", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(2).child(3).setText(0, QtGui.QApplication.translate("CityEX", "Windowsize", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(3).setText(0, QtGui.QApplication.translate("CityEX", "General Help", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.topLevelItem(3).child(0).setText(0, QtGui.QApplication.translate("CityEX", "Conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_tab4_help.setSortingEnabled(__sortingEnabled)
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.Help), QtGui.QApplication.translate("CityEX", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_global_cancel.setText(QtGui.QApplication.translate("CityEX", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_global_ok.setText(QtGui.QApplication.translate("CityEX", "OK", None, QtGui.QApplication.UnicodeUTF8))

